baseURL: 'https://dyuji.dev/'
languageCode: 'ja'
defaultContentLanguage: "ja"
hasCJKLanguage: true
title: 'dyuji.dev'
theme: 'PaperMod'

params:
  env: production
  defaultTheme: auto
  homeInfoParams:
    Title: "dyuji.dev"
    Content: >
        about software development so on.
  socialIcons:
      - name: github
        url: "https://github.com/d-yuji"
      - name: twitter
        url: "https://twitter.com/dyuji1"
      - name: email
        url: "https://forms.gle/JhcSaYd6bmRRqccbA"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: about
      name: about
      url: /about
      weight: 10
    - identifier: privacy policy
      name: privacy
      url: /privacy
      weight: 20
    - identifier: search
      name: search
      url: /search
    - identifier: tags
      name: tags
      url: /tags/

taxonomies:
  category: categories
  tag: tags
